// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2SvTFPGP9tEISRRzGjvtNz1bODHVtGbE',
    appId: '1:925444887724:web:3928db0709afb735287b09',
    messagingSenderId: '925444887724',
    projectId: 'chat-app-40dc4',
    authDomain: 'chat-app-40dc4.firebaseapp.com',
    storageBucket: 'chat-app-40dc4.appspot.com',
    measurementId: 'G-0TRVZ15TBD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLWNRbSoiR6dJMCIW8cIs4MtjiRLJ1N0A',
    appId: '1:925444887724:android:355795f66216eaa4287b09',
    messagingSenderId: '925444887724',
    projectId: 'chat-app-40dc4',
    storageBucket: 'chat-app-40dc4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzWIKCL8zVIuL5QoaM3h52TcsNs2yk5bs',
    appId: '1:925444887724:ios:44ae54b7768ede75287b09',
    messagingSenderId: '925444887724',
    projectId: 'chat-app-40dc4',
    storageBucket: 'chat-app-40dc4.appspot.com',
    iosBundleId: 'dev.flutterexplained.webrtc',
  );

}